# Generated by Django 2.0.7 on 2018-07-25 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Update',
            new_name='update',
        ),
    ]
