# Generated by Django 2.0.7 on 2018-07-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20180725_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='origin_md',
            field=models.TextField(default='#hahahah'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
