# Generated by Django 2.0.7 on 2018-08-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_article_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='username',
            field=models.CharField(default='public', max_length=128),
        ),
    ]
